name: Run K6 Test and Generate Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instala o K6 e configura o repositório
    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
        echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    # Executa o teste e gera o relatório HTML e stdout
    - name: Run K6 Load Test with HTML Report
      run: k6 run script.js

    # Upload do relatório HTML
    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: k6-html-report
        path: result.html
